
package com.example.demo.landray.com.landray.kmss.kmReviewWebserviceServiceSource;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.activation.URLDataSource;
import javax.xml.namespace.QName;
import java.lang.Exception;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2020-08-13T19:02:08.625+08:00
 * Generated source version: 2.4.2
 */
public final class IKmReviewWebserviceService_IKmReviewWebserviceServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.review.km.kmss.landray.com/", "IKmReviewWebserviceServiceService");

    private IKmReviewWebserviceService_IKmReviewWebserviceServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IKmReviewWebserviceServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        IKmReviewWebserviceServiceService ss = new IKmReviewWebserviceServiceService(wsdlURL, SERVICE_NAME);
        IKmReviewWebserviceService port = ss.getIKmReviewWebserviceServicePort();

        // 审批流程操作
        {
            System.out.println("Invoking approveProcess...");
            KmReviewParamterForm _approveProcess_arg0 = new KmReviewParamterForm();
            try {
                _approveProcess_arg0.setDocSubject("付款申请单");
                _approveProcess_arg0.setFdId("173eba721e9d3e97edbf1774c3c88bb8");
                _approveProcess_arg0.setFdTemplateId("15c7c08623cfcb55946daa847bcb6efb");
                _approveProcess_arg0.setDocCreator("{\"PersonNo\": \"00005453\"}");
                String flowParam = "{operationType:\"handler_pass\",auditNode:\"同意\",futureNodeId:\"N78\",changeNodeHandlers:[\"N78:17370a85e82dedba2d42fae406f8df11;17370a85f8f573fbfebf22f4a2eac7f0\"]}";
                _approveProcess_arg0.setFlowParam(flowParam);
                String _approveProcess__return = port.approveProcess(_approveProcess_arg0);
                System.out.println("approveProcess.result=" + _approveProcess__return);

            } catch (Exception_Exception e) {
                System.out.println("Expected exception: Exception has occurred.");
                System.out.println(e.toString());
            }
        }

        // 更新流程表单数据
//        {
//            System.out.println("Invoking updateReviewInfo...");
//            KmReviewParamterForm _updateReviewInfo_arg0 = new KmReviewParamterForm();
//            try {
//                String _updateReviewInfo__return = port.updateReviewInfo(_updateReviewInfo_arg0);
//                System.out.println("updateReviewInfo.result=" + _updateReviewInfo__return);
//
//            } catch (Exception_Exception e) {
//                System.out.println("Expected exception: Exception has occurred.");
//                System.out.println(e.toString());
//            }
//        }

        // 启动审批流程
//        {
//            System.out.println("Invoking addReview...");
//            KmReviewParamterForm form = new KmReviewParamterForm();
//            try {
//                // 文档模板id
//                form.setFdTemplateId("15c7c08623cfcb55946daa847bcb6efb");
//                // 文档标题
//                form.setDocSubject("付款申请单2");
//                // 流程发起人
//                form.setDocCreator("{\"PersonNo\": \"00005756\"}");
//                // 文档关键字
////            form.setFdKeyword("[\"物料\", \"采购\"]");
//                // 流程表单
//                String formValues = "{\"fd_2fdec3b42db6b0\":\"17370a7db46409d1d4dd02e4e83bc6d0\", \"fd_314f3cca32d552\":\"1699e43cfc5b06e118e1e1c47a7a5acd\",\"fd_2fdec3b8b4242a\":\"2020-08-14\"," +
//                        "\"fd_341c050386f954\":\"100.02\",\"fd_341c057a02ad2a\":\"现金\",\"fd_341c07e33ea8ae\":\"1\",\"fd_34127eaaf8fa44\":\"张三\"," +
//                        "\"fd_34127ec23270c2\":\"6215581813000207184\",\"fd_341c05d124f65a\":\"合同\"}";
//                form.setFormValues(formValues);
//                // 流程参数
//                String flowParam = "{auditNode:\"请审核\", futureNodeId:\"N75\", changeNodeHandlers:[\"N75:17370a85e82dedba2d42fae406f8df11;17370a85f8f573fbfebf22f4a2eac7f0\"]}";
//                form.setFlowParam(flowParam);
//
//                List<AttachmentForm> attForms = createAllAtts();
//                form.getAttachmentForms().addAll(attForms);
//
//                String _addReview__return = port.addReview(form);
//                System.out.println("addReview.result=" + _addReview__return);
//
//            } catch (Exception_Exception e) {
//                System.out.println("Expected exception: Exception has occurred.");
//                System.out.println(e.toString());
//            }
//        }

        System.exit(0);
    }


    /**
     * 创建附件列表
     */
    static List<AttachmentForm> createAllAtts() throws Exception {

        List<AttachmentForm> attForms = new ArrayList<AttachmentForm>();

        String fileName = "31AE88-201802.xlsx";
        AttachmentForm attForm01 = createUrlFile(fileName);
        fileName = "测试.docx";
        AttachmentForm attForm02 = createAtt(fileName);

        attForms.add(attForm01);
        attForms.add(attForm02);

        return attForms;
    }

    /**
     * 创建附件对象
     */
    static AttachmentForm createAtt(String fileName) throws Exception {
        AttachmentForm attForm = new AttachmentForm();
        attForm.setFdFileName(fileName);
        // 设置附件关键字，表单模式下为附件控件的id
        attForm.setFdKey("fd_2ff647e86b4688");
        DataSource dataSource = new FileDataSource("C:\\Users\\ming.zhang2\\Desktop\\" + fileName);
        DataHandler dataHandler = new DataHandler(dataSource);
        attForm.setFdAttachment(dataHandler);

        return attForm;
    }

    /**
     * 创建Url
     */
    static AttachmentForm createUrlFile(String fileName) throws Exception {
        AttachmentForm attForm = new AttachmentForm();
        attForm.setFdFileName(fileName);
        // 设置附件关键字，表单模式下为附件控件的id
        attForm.setFdKey("fd_2ff647e86b4688");
        URL url = new URL("http://files.winit.com.cn/uploads/ftp/account_ftp/2018/ups/original_bill/31AE88-201802.xlsx");
        DataSource dataSource = new URLDataSource(url);
        DataHandler dataHandler = new DataHandler(dataSource);
        attForm.setFdAttachment(dataHandler);
        return attForm;
    }

    /**
     * 将文件转换为字节编码
     */
    static byte[] file2bytes(String fileName) throws Exception {
        InputStream in = new FileInputStream(fileName);
        byte[] data = new byte[in.available()];

        try {
            in.read(data);
        } finally {
            try {
                in.close();
            } catch (IOException ex) {
            }
        }

        return data;
    }

}
