package com.example.demo.landray.com.landray.kmss.kmReviewWebserviceServiceSource;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2020-08-13T19:02:08.692+08:00
 * Generated source version: 2.4.2
 *
 */
@WebService(targetNamespace = "http://webservice.review.km.kmss.landray.com/", name = "IKmReviewWebserviceService")
@XmlSeeAlso({ObjectFactory.class})
public interface IKmReviewWebserviceService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "approveProcess", targetNamespace = "http://webservice.review.km.kmss.landray.com/", className = "com.example.demo.landray.com.landray.kmss.kmReviewWebserviceServiceSource.ApproveProcess")
    @WebMethod
    @ResponseWrapper(localName = "approveProcessResponse", targetNamespace = "http://webservice.review.km.kmss.landray.com/", className = "com.example.demo.landray.com.landray.kmss.kmReviewWebserviceServiceSource.ApproveProcessResponse")
    public java.lang.String approveProcess(
            @WebParam(name = "arg0", targetNamespace = "")
                    KmReviewParamterForm arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateReviewInfo", targetNamespace = "http://webservice.review.km.kmss.landray.com/", className = "com.example.demo.landray.com.landray.kmss.kmReviewWebserviceServiceSource.UpdateReviewInfo")
    @WebMethod
    @ResponseWrapper(localName = "updateReviewInfoResponse", targetNamespace = "http://webservice.review.km.kmss.landray.com/", className = "com.example.demo.landray.com.landray.kmss.kmReviewWebserviceServiceSource.UpdateReviewInfoResponse")
    public java.lang.String updateReviewInfo(
            @WebParam(name = "arg0", targetNamespace = "")
                    KmReviewParamterForm arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addReview", targetNamespace = "http://webservice.review.km.kmss.landray.com/", className = "com.example.demo.landray.com.landray.kmss.kmReviewWebserviceServiceSource.AddReview")
    @WebMethod
    @ResponseWrapper(localName = "addReviewResponse", targetNamespace = "http://webservice.review.km.kmss.landray.com/", className = "com.example.demo.landray.com.landray.kmss.kmReviewWebserviceServiceSource.AddReviewResponse")
    public java.lang.String addReview(
            @WebParam(name = "arg0", targetNamespace = "")
                    KmReviewParamterForm arg0
    ) throws Exception_Exception;
}
