
package com.example.demo.landray.sysNotifyTodoWebServiceSource;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import com.alibaba.fastjson.JSON;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2020-08-14T15:24:33.737+08:00
 * Generated source version: 2.4.2
 */
public final class ISysNotifyTodoWebService_ISysNotifyTodoWebServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.notify.sys.kmss.landray.com/", "ISysNotifyTodoWebServiceService");

    private ISysNotifyTodoWebService_ISysNotifyTodoWebServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ISysNotifyTodoWebServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ISysNotifyTodoWebServiceService ss = new ISysNotifyTodoWebServiceService(wsdlURL, SERVICE_NAME);
        ISysNotifyTodoWebService port = ss.getISysNotifyTodoWebServicePort();

        // 获取待办
        {
            System.out.println("Invoking getTodo...");
            NotifyTodoGetContext _getTodo_arg0 = new NotifyTodoGetContext();
            try {
                _getTodo_arg0.setTargets("{\"PersonNo\": \"00005756\"}");
                _getTodo_arg0.setType(3);
                _getTodo_arg0.setPageNo(1);
                _getTodo_arg0.setRowSize(10000);
//                _getTodo_arg0.setOtherCond("[{\"modelId\": \"173eba1933c12fe9d745f284fce999d9\"}]");
                NotifyTodoAppResult _getTodo__return = port.getTodo(_getTodo_arg0);
                System.out.println("getTodo.result=" + JSON.toJSONString(_getTodo__return));

            } catch (Exception_Exception e) {
                System.out.println("Expected exception: Exception has occurred.");
                System.out.println(e.toString());
            }
        }
        // 设为已办
        {
            System.out.println("Invoking setTodoDone...");
            NotifyTodoRemoveContext _setTodoDone_arg0 = new NotifyTodoRemoveContext();
            try {
                _setTodoDone_arg0.setTargets("{\"PersonNo\": \"00005453\"}");
                _setTodoDone_arg0.setAppName(null);
                _setTodoDone_arg0.setModelName("com.landray.kmss.km.review.model.KmReviewMain");
                _setTodoDone_arg0.setModelId("173eba8e1adeafa163b894d45cbbb863");
                _setTodoDone_arg0.setOptType(1);
                NotifyTodoAppResult _setTodoDone__return = port.setTodoDone(_setTodoDone_arg0);
                System.out.println("setTodoDone.result=" + JSON.toJSONString(_setTodoDone__return));

            } catch (Exception_Exception e) {
                System.out.println("Expected exception: Exception has occurred.");
                System.out.println(e.toString());
            }
        }
        // 获取待办数量
//        {
//            System.out.println("Invoking getTodoCount...");
//            NotifyTodoGetCountContext _getTodoCount_arg0 = new NotifyTodoGetCountContext();
//            try {
//                _getTodoCount_arg0.setTarget("{\"PersonNo\": \"00005453\"}");
//                _getTodoCount_arg0.setTypes("[{\"type\":1}]");
//                NotifyTodoAppResult _getTodoCount__return = port.getTodoCount(_getTodoCount_arg0);
//                System.out.println("getTodoCount.result=" + JSON.toJSONString(_getTodoCount__return));
//
//            } catch (Exception_Exception e) {
//                System.out.println("Expected exception: Exception has occurred.");
//                System.out.println(e.toString());
//            }
//        }

//        {
//            System.out.println("Invoking updateTodo...");
//            NotifyTodoUpdateContext _updateTodo_arg0 = new NotifyTodoUpdateContext();
//            try {
//                NotifyTodoAppResult _updateTodo__return = port.updateTodo(_updateTodo_arg0);
//                System.out.println("updateTodo.result=" + _updateTodo__return);
//
//            } catch (Exception_Exception e) {
//                System.out.println("Expected exception: Exception has occurred.");
//                System.out.println(e.toString());
//            }
//        }
//
//        {
//            System.out.println("Invoking deleteTodo...");
//            NotifyTodoRemoveContext _deleteTodo_arg0 = new NotifyTodoRemoveContext();
//            try {
//                NotifyTodoAppResult _deleteTodo__return = port.deleteTodo(_deleteTodo_arg0);
//                System.out.println("deleteTodo.result=" + _deleteTodo__return);
//
//            } catch (Exception_Exception e) {
//                System.out.println("Expected exception: Exception has occurred.");
//                System.out.println(e.toString());
//            }
//        }
//        {
//            System.out.println("Invoking sendTodo...");
//            NotifyTodoSendContext _sendTodo_arg0 = new NotifyTodoSendContext();
//            try {
//                NotifyTodoAppResult _sendTodo__return = port.sendTodo(_sendTodo_arg0);
//                System.out.println("sendTodo.result=" + _sendTodo__return);
//
//            } catch (Exception_Exception e) {
//                System.out.println("Expected exception: Exception has occurred.");
//                System.out.println(e.toString());
//            }
//        }

        System.exit(0);
    }

}
