package com.example.demo.landray.com.landray.kmss.lbpmFlowLogGetWebServiceSource;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2020-08-14T14:52:41.780+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://webservice.server.etl.lbpm.flowstatplug.dbcenter.kmss.landray.com/", name = "ILbpmFlowLogGetWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface ILbpmFlowLogGetWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getFlowCategoryIsTemplate", targetNamespace = "http://webservice.server.etl.lbpm.flowstatplug.dbcenter.kmss.landray.com/", className = "com.example.demo.landray.com.landray.kmss.lbpmFlowLogGetWebServiceSource.GetFlowCategoryIsTemplate")
    @WebMethod
    @ResponseWrapper(localName = "getFlowCategoryIsTemplateResponse", targetNamespace = "http://webservice.server.etl.lbpm.flowstatplug.dbcenter.kmss.landray.com/", className = "com.example.demo.landray.com.landray.kmss.lbpmFlowLogGetWebServiceSource.GetFlowCategoryIsTemplateResponse")
    public LbpmFlowLogResult getFlowCategoryIsTemplate(
            @WebParam(name = "arg0", targetNamespace = "")
                    LbpmFlowLogContext arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getFlowLog", targetNamespace = "http://webservice.server.etl.lbpm.flowstatplug.dbcenter.kmss.landray.com/", className = "com.example.demo.landray.com.landray.kmss.lbpmFlowLogGetWebServiceSource.GetFlowLog")
    @WebMethod
    @ResponseWrapper(localName = "getFlowLogResponse", targetNamespace = "http://webservice.server.etl.lbpm.flowstatplug.dbcenter.kmss.landray.com/", className = "com.example.demo.landray.com.landray.kmss.lbpmFlowLogGetWebServiceSource.GetFlowLogResponse")
    public LbpmFlowLogResult getFlowLog(
            @WebParam(name = "arg0", targetNamespace = "")
                    LbpmFlowLogContext arg0
    ) throws Exception_Exception;
}
