
package com.example.demo.landray.com.landray.kmss.km.review.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2020-08-13T19:02:08.625+08:00
 * Generated source version: 2.4.2
 * 
 */
public final class IKmReviewWebserviceService_IKmReviewWebserviceServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.review.km.kmss.landray.com/", "IKmReviewWebserviceServiceService");

    private IKmReviewWebserviceService_IKmReviewWebserviceServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IKmReviewWebserviceServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        IKmReviewWebserviceServiceService ss = new IKmReviewWebserviceServiceService(wsdlURL, SERVICE_NAME);
        IKmReviewWebserviceService port = ss.getIKmReviewWebserviceServicePort();  
        
//        {
//        System.out.println("Invoking approveProcess...");
//        KmReviewParamterForm _approveProcess_arg0 = new KmReviewParamterForm();
//        try {
//            String _approveProcess__return = port.approveProcess(_approveProcess_arg0);
//            System.out.println("approveProcess.result=" + _approveProcess__return);
//
//        } catch (Exception_Exception e) {
//            System.out.println("Expected exception: Exception has occurred.");
//            System.out.println(e.toString());
//        }
//            }
//        {
//        System.out.println("Invoking updateReviewInfo...");
//        KmReviewParamterForm _updateReviewInfo_arg0 = new KmReviewParamterForm();
//        try {
//            String _updateReviewInfo__return = port.updateReviewInfo(_updateReviewInfo_arg0);
//            System.out.println("updateReviewInfo.result=" + _updateReviewInfo__return);
//
//        } catch (Exception_Exception e) {
//            System.out.println("Expected exception: Exception has occurred.");
//            System.out.println(e.toString());
//        }
//            }
        {
        System.out.println("Invoking addReview...");
        KmReviewParamterForm form = new KmReviewParamterForm();
        try {
            // 文档模板id
            form.setFdTemplateId("169e1e9094824b702b6f74f453bb39b5");
            // 文档标题
            form.setDocSubject("物料采购申请单");
            // 流程发起人
            form.setDocCreator("{\"PersonNo\": \"00012\"}");
            // 文档关键字
            form.setFdKeyword("[\"物料\", \"采购\"]");
            // 流程表单
            String formValues = "{\"fd_2eddbf023c8292\":\"张三\", \"fd_2edd2f83f68242\":\"咨询部\", \"fd_2edd2fa69f6fc6\":\"\", \"fd_2eddbf09f9bc96\":\"2011-10-26\", \"fd_2edd2fb18e7f90\":{\"fd_2edd2fb18e7f90.fd_2eddbef4da4688\":[\"555555\",\"777777\"], \"fd_2edd2fb18e7f90.fd_2edd2fc8001062\":[\"444444\",\"666666\"], \"fd_2edd2fb18e7f90.fdId\":[\"1332472122898ac618f3e22460cab595\",\"13324721228b50c184d82c44ceca5301\"]}}";
            form.setFormValues(formValues);
            // 流程参数
            String flowParam = "{auditNode:\"请审核\", futureNodeId:\"N7\", changeNodeHandlers:[\"N7:1183b0b84ee4f581bba001c47a78b2d9;131d019fbac792eab0f0a684c8a8d0ec\"]}";
            form.setFlowParam(flowParam);
            String _addReview__return = port.addReview(form);
            System.out.println("addReview.result=" + _addReview__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
